apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  clusterIP: None
  ports:
    - name: intra
      port: 7000
    - name: tls
      port: 7001
    - name: jmx
      port: 7199
    - name: cql
      port: 9042
    - name: thrift
      port: 9160
  selector:
    app: cassandra
